// frontend/src/App.jsx
import React from 'react';
import resumeData from './data/info.json';
import Section from './components/Section';
import './index.css';

function App() {
  // Guard clause if json is empty or missing
  if (!resumeData.name) {
    return <div className="loading">No resume data found. Run the backend parser first.</div>;
  }

  return (
    <div className="container">
      <header className="header">
        <h1>{resumeData.name}</h1>
        <p className="email">{resumeData.email}</p>
        <p className="summary">{resumeData.summary}</p>
      </header>

      <main>
        <Section title="Skills" items={resumeData.skills} isList={true} />
        <Section title="Experience" items={resumeData.experience} />
        <Section title="Education" items={resumeData.education} />
      </main>
      
      <footer>
        <p>Generated by Go-Resume-Scraper</p>
      </footer>
    </div>
  );
}

export default App;